# Generated by Django 3.0.8 on 2020-07-17 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20200717_1326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='firstname',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='lastname',
        ),
    ]
